// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class AdRewardsServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public AdRewardsServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.PlayerEconomyData> HandleGrantVideoAdReward(string adToken)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerEconomyData>(
                "TempleRunUGSCloud",
                "HandleGrantVideoAdReward",
                new Dictionary<string, object>()
                {
                    {"adToken", adToken},
                });
        }
    }
}
