// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class AllPlayersServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public AllPlayersServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<List<TempleRunUGSCloud.Models.Player>> GetPlayerList()
        {
            return await k_Service.CallModuleEndpointAsync<List<TempleRunUGSCloud.Models.Player>>(
                "TempleRunUGSCloud",
                "GetPlayerList",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
