// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class CommandBatchingService_AreaUpgradablesBindings
    {
        readonly ICloudCodeService k_Service;
        public CommandBatchingService_AreaUpgradablesBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.CommandReward> ProcessAreaCompleteCommandBatch(List<string> timeSignedCommandKeys)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.CommandReward>(
                "TempleRunUGSCloud",
                "ProcessAreaCompleteCommandBatch",
                new Dictionary<string, object>()
                {
                    {"timeSignedCommandKeys", timeSignedCommandKeys},
                });
        }
    }
}
