// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class DailyRewardsStatusServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public DailyRewardsStatusServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.DailyRewardsResult> GetDailyRewardsStatus()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.DailyRewardsResult>(
                "TempleRunUGSCloud",
                "GetDailyRewardsStatus",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
