// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class FriendsServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public FriendsServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<List<TempleRunUGSCloud.Models.Player>> GetFriends()
        {
            return await k_Service.CallModuleEndpointAsync<List<TempleRunUGSCloud.Models.Player>>(
                "TempleRunUGSCloud",
                "GetFriends",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<List<TempleRunUGSCloud.Models.Player>> AddFriend(string friendPlayerId)
        {
            return await k_Service.CallModuleEndpointAsync<List<TempleRunUGSCloud.Models.Player>>(
                "TempleRunUGSCloud",
                "AddFriend",
                new Dictionary<string, object>()
                {
                    {"friendPlayerId", friendPlayerId},
                });
        }

        public async Task<List<TempleRunUGSCloud.Models.Player>> RemoveFriend(string friendPlayerId)
        {
            return await k_Service.CallModuleEndpointAsync<List<TempleRunUGSCloud.Models.Player>>(
                "TempleRunUGSCloud",
                "RemoveFriend",
                new Dictionary<string, object>()
                {
                    {"friendPlayerId", friendPlayerId},
                });
        }
    }
}
