// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GiftHeartCooldownServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public GiftHeartCooldownServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<bool> CheckGiftHeartReplenish()
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "TempleRunUGSCloud",
                "CheckGiftHeartReplenish",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
