// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class HandleProfileChangeServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public HandleProfileChangeServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> ChangeDisplayName(string newDisplayName)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "TempleRunUGSCloud",
                "ChangeDisplayName",
                new Dictionary<string, object>()
                {
                    {"newDisplayName", newDisplayName},
                });
        }

        public async Task<bool> ChangeProfilePicture(TempleRunUGSCloud.Models.ProfilePictureChangeRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "TempleRunUGSCloud",
                "ChangeProfilePicture",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }
    }
}
