// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class LootBoxCooldownServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public LootBoxCooldownServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.LootBoxCooldownResult> CheckLootBoxCooldown()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.LootBoxCooldownResult>(
                "TempleRunUGSCloud",
                "CheckLootBoxCooldown",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
