// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class LootBoxServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public LootBoxServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.LootBoxResult> ClaimLootBox()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.LootBoxResult>(
                "TempleRunUGSCloud",
                "ClaimLootBox",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
