// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerGiftsServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerGiftsServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.PlayerData> HandleSendPlayerGift(string recipientPlayerId)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerData>(
                "TempleRunUGSCloud",
                "HandleSendPlayerGift",
                new Dictionary<string, object>()
                {
                    {"recipientPlayerId", recipientPlayerId},
                });
        }

        public async Task<TempleRunUGSCloud.Models.PlayerData> CheckReceivedGifts()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerData>(
                "TempleRunUGSCloud",
                "CheckReceivedGifts",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
