// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class StoreServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public StoreServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.PlayerEconomyData> HandlePurchase(string productId, string receipt, string transactionId)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerEconomyData>(
                "TempleRunUGSCloud",
                "HandlePurchase",
                new Dictionary<string, object>()
                {
                    {"productId", productId},
                    {"receipt", receipt},
                    {"transactionId", transactionId},
                });
        }

        public async Task<TempleRunUGSCloud.Models.PlayerEconomyData> HandleFreeCoinPackPurchase()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerEconomyData>(
                "TempleRunUGSCloud",
                "HandleFreeCoinPackPurchase",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
