// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class UpgradableAreaItemsServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public UpgradableAreaItemsServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.PlayerData> HandleUnlock(int areaId, int itemId)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerData>(
                "TempleRunUGSCloud",
                "HandleUnlock",
                new Dictionary<string, object>()
                {
                    {"areaId", areaId},
                    {"itemId", itemId},
                });
        }

        public async Task<TempleRunUGSCloud.Models.PlayerData> HandleUpgrade(int areaId, int itemId)
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerData>(
                "TempleRunUGSCloud",
                "HandleUpgrade",
                new Dictionary<string, object>()
                {
                    {"areaId", areaId},
                    {"itemId", itemId},
                });
        }
    }
}
