// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GlobalScoreClientBindings
    {
        readonly ICloudCodeService k_Service;
        public GlobalScoreClientBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> UpdateGlobalScore(int increment)
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "BlocksGameModule",
                "UpdateGlobalScore",
                new Dictionary<string, object>()
                {
                    {"increment", increment},
                });
        }

        public async Task<int> GetGlobalScore()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "BlocksGameModule",
                "GetGlobalScore",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
