// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class LeaderboardClientBindings
    {
        readonly ICloudCodeService k_Service;
        public LeaderboardClientBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<List<Unity.Services.Leaderboards.Model.LeaderboardEntry>> GetScoresAsync(string leaderboardId, int limitParam, bool isGlobal)
        {
            return await k_Service.CallModuleEndpointAsync<List<Unity.Services.Leaderboards.Model.LeaderboardEntry>>(
                "BlocksGameModule",
                "GetScoresAsync",
                new Dictionary<string, object>()
                {
                    {"leaderboardId", leaderboardId},
                    {"limitParam", limitParam},
                    {"isGlobal", isGlobal},
                });
        }

        public async Task AddPlayerScoreAsync(string leaderboardId, double score)
        {
            await k_Service.CallModuleEndpointAsync(
                "BlocksGameModule",
                "AddPlayerScoreAsync",
                new Dictionary<string, object>()
                {
                    {"leaderboardId", leaderboardId},
                    {"score", score},
                });
        }
    }
}
