// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class NumberGameClientBindings
    {
        readonly ICloudCodeService k_Service;
        public NumberGameClientBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<BlocksGameModule.Leaderboards.NumberGameResult> RequestGoalAndScore(string leaderboardId, int guess)
        {
            return await k_Service.CallModuleEndpointAsync<BlocksGameModule.Leaderboards.NumberGameResult>(
                "BlocksGameModule",
                "RequestGoalAndScore",
                new Dictionary<string, object>()
                {
                    {"leaderboardId", leaderboardId},
                    {"guess", guess},
                });
        }
    }
}
