// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class LeaderboardAdminFunctionsBindings
    {
        readonly ICloudCodeService k_Service;
        public LeaderboardAdminFunctionsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SetupFakeEntries(string lbName, int count, int min, int max)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "BlocksAdminModule",
                "SetupFakeEntries",
                new Dictionary<string, object>()
                {
                    {"lbName", lbName},
                    {"count", count},
                    {"min", min},
                    {"max", max},
                });
        }
    }
}
